[phases.setup]
commands = [
  "pip install -r requirements.txt",
]

[phases.build]
commands = [
  "python manage.py collectstatic --noinput",
]

[phases.start]
command = "gunicorn shakes.wsgi --bind 0.0.0.0:$PORT"
